version: 2

jobs:
  build:
    docker:
      - image: circleci/node:17.2.0-stretch
    steps:
      - checkout
      - run:
          name: Install packages
          command: yarn install
      - run:
          name: Build, Minify, & Run app
          command: yarn deploy
